sudo: required

language: cpp

cache:
  directories:
    - /opt/devkitpro/pacman/var/cache/pacman/pkg/

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules # Travis can't deal with the user 'git'...
  - git submodule update --init --recursive
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb
  - sudo dkp-pacman -S switch-{dev,curl,freetype} --noconfirm
  - source /etc/profile.d/devkit-env.sh
  - sudo make install -C ./libs/libnx/nx

script:
  - make

before_deploy:
  - export TRAVIS_TAG=snapshot
  
deploy:
  provider: releases
  prerelease: true
  api_key: $GITHUB_TOKEN
  file: out/EdiZon.nro
  skip_cleanup: true
  overwrite: true
  name: "Snapshot Build"
  body: "This build could be unstable, you may install and use it at your own risk."
  on:
    branch: master