name: Build EdiZon

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v1
    - name: Building EdiZon
      run: make
